### ISSUE TITLE
Register definitions for factory option bytes

### ISSUE THREAD

**Issue by rnestler** [stm32-rs/stm32l0xx-hal#120]
I'm trying to use the internal ADC reference to monitor VDDA. To do that I need the `VREFINT_CAL` value from the factory options. The factory option location aren't available in the SVD file (probably because they aren't peripheral) so they are not accessible.

Would it make sense to add register like definitions to the HAL or the PAC for the factory option location?

For reference a section from the STM32L071xx datasheet:

![vrefint_cal_location](https://user-images.githubusercontent.com/1435346/89347591-60ccaf00-d6ab-11ea-85f3-e684e3827552.png)

and from the STM32L0x1 reference manual:

![vrefint_cal](https://user-images.githubusercontent.com/1435346/89347592-61654580-d6ab-11ea-9aed-b0e2810c41a2.png)

cc @dbrgn

**Comment by dbrgn** [comment]
This field is part of the NVM bus:

![2020-08-05-091949_976x502_scrot](https://user-images.githubusercontent.com/105168/89383473-d7de6380-d6fc-11ea-8901-723895a33273.png)

I think it makes sense exposing factory option bytes and user option bytes through the HAL, but I'm not sure where the best place for that would be... Maybe an `nvm` module?

**Comment by dbrgn** [comment]
@adamgreig @hannobraun are these fields exposed in one of the other HALs that you're aware of?

**Comment by adamgreig** [comment]
F4 has it in `signature`: https://github.com/stm32-rs/stm32f4xx-hal/blob/master/src/signature.rs

**Comment by dbrgn** [comment]
@adamgreig nice, thanks! That could probably be re-used for L0 as well.

Is the term "signature" commonly used for this type of information (calibration data)?

**Comment by adamgreig** [comment]
I expect it came about because that module also covers reading the device unique ID (another random memory address you can't get from the SVD) and the device flash size, both of which are more 'signature'-esque. I haven't seen it for cal data but it makes sense alongside the other factory-written information I guess.

**Comment by dbrgn** [comment]
Maybe the module could be called `nvm` or `factory` instead.

**Comment by adamgreig** [comment]
Or `calibration` or `caldata`? But if you include the unique ID and flash size I think `signature` is OK, it still implies some sort of unique data about this particular chip.

That all said we also have https://github.com/stm32-rs/stm32-device-signature which provides access to unique ID and flash size (and is called `signature`) across many families including L0; perhaps the HAL could re-export that for unique ID and flash and then have a new module for cal data? I'm not sure about `nvm` since it's a bit generic and a `factory` module sounds like it should be a factory rather than contain factory data, though.

**Comment by dbrgn** [comment]
Calibration data is provided in a new `calibration` module in #121.

Regarding the signature data, I'm not sure if it's worth it to pull in an external crate for [such a simple module](https://github.com/stm32-rs/stm32-device-signature/blob/master/src/lib.rs)... I'd tend towards copy-pasting the few lines into the HAL instead (with proper credits to @disasm of course). What do you think?

**Comment by adamgreig** [comment]
No objections from me!
