### ISSUE TITLE
adc to internal temperature

### ISSUE THREAD

**Issue by pdgilbert** [stm32-rs/stm32l0xx-hal#161]
Is it possible to read the internal temperature with adc. I think it is connected to internal channel ADC_IN18 but I don't see how to specify that. (Newbie, so I may just be doing something stupid.)

**Comment by hannobraun** [comment]
The internal temperature sensor is represented by `adc::VTemp`. I'm not sure how to use it, but it has an `enable` method, and presumably can be treated like any other channel after that.

It would be great if we had an example showing this in the repository.

**Comment by pdgilbert** [comment]
Ok, I got it to build. I just used VTemp as the channel and didn't need to do any `enable` for it to build. I don't have hardware to test that this actually works. I can do a PR with an example if you like,  but not testing on hardware is a caveat.

**Comment by hannobraun** [comment]
Well, I guess having an example that points users in the right direction would be valuable, even if it's not tested. I'd merge your PR, as long as the example has prominent comments that clearly state it needs testing and might possibly not work.

**Comment by pdgilbert** [comment]
I will do a PR shortly. In addition to saying it has not been tested I will suggest if anyone does test it then they could report results here (issue #161). I'll also add a comment about my site https://github.com/pdgilbert/eg_stm_hal/ which has `setup()` functions for other devices, and several other examples too. Let me know if you would prefer that I omit that.
Thanks for your help.

**Comment by cscherrNT** [comment]
Hello. I was just trying to get temperature reading to work on my `STM32L053R8T6` (`NUCLEO-L053R8`). I have not compied the exact code of the example, but simplified it a bit since I'm rather new to embedded and embedded Rust.

I just want to report that I'm getting constant values when reading from `VTemp` with the ADC compared to reading from `PB1`. `VTemp` Gives me some constant value while `PB1` fluctuates. `PB1` seems not random, but I'm not sure if it's actually the temperature either. 

I one of the datasheets by ST mentions that the processors temperature behavior is specific to each chip, and that there are read only reference values for known temperatures to compare. [Source](https://www.st.com/resource/en/datasheet/stm32l053r8.pdf), Table 6 in Secion 3.13 "Temperature sensor"

[Here](https://git.cscherr.de/PlexSheep/nucleo-l053r8/src/commit/f6d7a67683fd846bc7c9ac28bcd41e48af84498f/examples/temperature.rs) is the code I used.
